# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c3103596c40a7cc1f9305c683512097b01ce8904e7e71113159e3055d003b110855ea7d7ab073a4bd08bd4b270521ff9839081d078e285a5d222a9fa63e6e7b

test:
  secret_key_base: 43257cc6ca65b72b8aa622b42ad0ae582f260d93d8eaffec52999367d463654bbd8efaa46dd54dc5e0cba514481c5273972166555580b7ab525993dd9ad4a5a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
